/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JPanel;
import Demo.User;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author Lohitha Atluri
 */
public class View extends javax.swing.JPanel {

    /**
     * Creates new form Form
     */
    private User newUser;
    public View(User newUser) {
        initComponents();
        this.newUser = newUser;
        populateData();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderbuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        FLabel = new javax.swing.JLabel();
        LLabel = new javax.swing.JLabel();
        ALabel = new javax.swing.JLabel();
        GLabel = new javax.swing.JLabel();
        ELabel = new javax.swing.JLabel();
        TLabel = new javax.swing.JLabel();
        MLabel = new javax.swing.JLabel();
        FTextField = new javax.swing.JTextField();
        ATextField = new javax.swing.JTextField();
        LTextField = new javax.swing.JTextField();
        mRadioButton = new javax.swing.JRadioButton();
        fRadioButton = new javax.swing.JRadioButton();
        oRadioButton = new javax.swing.JRadioButton();
        ETextField = new javax.swing.JTextField();
        TComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        MTextArea = new javax.swing.JTextArea();
        PLabel = new javax.swing.JLabel();
        UButton = new javax.swing.JButton();
        alab = new javax.swing.JLabel();
        flab = new javax.swing.JLabel();
        llab = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));

        TitleLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("View  Details");

        FLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FLabel.setText("FirstName:");

        LLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LLabel.setText("LastName:");

        ALabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ALabel.setText("Age:");

        GLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GLabel.setText("Gender:");

        ELabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ELabel.setText("Email:");

        TLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TLabel.setText("Type:");

        MLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MLabel.setText("Message:");

        FTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FTextFieldKeyPressed(evt);
            }
        });

        ATextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ATextFieldKeyPressed(evt);
            }
        });

        LTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LTextFieldKeyPressed(evt);
            }
        });

        GenderbuttonGroup.add(mRadioButton);
        mRadioButton.setText("Male");

        GenderbuttonGroup.add(fRadioButton);
        fRadioButton.setText("Female");

        GenderbuttonGroup.add(oRadioButton);
        oRadioButton.setText("Other");

        TComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "Visitor" }));
        TComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TComboBoxActionPerformed(evt);
            }
        });

        MTextArea.setColumns(20);
        MTextArea.setRows(5);
        jScrollPane1.setViewportView(MTextArea);

        PLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PLabel.setText("Photo:");

        UButton.setText("upload");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ALabel)
                                .addComponent(LLabel)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MLabel)
                                    .addComponent(ELabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PLabel, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(alab))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(flab))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(llab))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mRadioButton)
                                .addGap(32, 32, 32)
                                .addComponent(fRadioButton)
                                .addGap(28, 28, 28)
                                .addComponent(oRadioButton))
                            .addComponent(ETextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(TitleLabel)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FLabel)
                    .addComponent(FTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flab))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LLabel)
                    .addComponent(LTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llab))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALabel)
                    .addComponent(ATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alab))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mRadioButton)
                        .addComponent(fRadioButton)
                        .addComponent(oRadioButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ELabel)
                    .addComponent(ETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TLabel)
                    .addComponent(TComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLabel)
                    .addComponent(UButton))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ATextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ATextFieldKeyPressed
        String PATTERN="^[0-9]{0,100}";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ATextField.getText());
        if(!match.matches()){
            alab.setText("Incorrect Format");
        }
        else{
            alab.setText(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ATextFieldKeyPressed

    private void TComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TComboBoxActionPerformed

    private void FTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FTextFieldKeyPressed
       String PATTERN="^[a-zA-Z]{a,z}{A,Z}";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ATextField.getText());
        if(!match.matches()){
            flab.setText("Incorrect Format");
        }
        else{
            flab.setText(null);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_FTextFieldKeyPressed

    private void LTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LTextFieldKeyPressed
       String PATTERN="^[a-zA-Z]{a,z}{A,Z}";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(ATextField.getText());
        if(!match.matches()){
            llab.setText("Incorrect Format");
        }
        else{
            llab.setText(null);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_LTextFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALabel;
    private javax.swing.JTextField ATextField;
    private javax.swing.JLabel ELabel;
    private javax.swing.JTextField ETextField;
    private javax.swing.JLabel FLabel;
    private javax.swing.JTextField FTextField;
    private javax.swing.JLabel GLabel;
    private javax.swing.ButtonGroup GenderbuttonGroup;
    private javax.swing.JLabel LLabel;
    private javax.swing.JTextField LTextField;
    private javax.swing.JLabel MLabel;
    private javax.swing.JTextArea MTextArea;
    private javax.swing.JLabel PLabel;
    private javax.swing.JComboBox<String> TComboBox;
    private javax.swing.JLabel TLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton UButton;
    private javax.swing.JLabel alab;
    private javax.swing.JRadioButton fRadioButton;
    private javax.swing.JLabel flab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel llab;
    private javax.swing.JRadioButton mRadioButton;
    private javax.swing.JRadioButton oRadioButton;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        
      FTextField.setText(this.newUser.getFirstName());
      LTextField.setText(this.newUser.getLastName());
      ATextField.setText(this.newUser.getAge());
      ETextField.setText(this.newUser.getEmail());
      MTextArea.setText(this.newUser.getMessage());
      TComboBox.setSelectedItem(this.newUser.getType());
      //GenderbuttonGroup.getButton(this.newUser.getGender());
      PLabel.setIcon(this.newUser.getPhoto());
      //GenderbuttonGroup.setGender.getSelection().getActionCommand()(this .newUser.grtGender));
    }
}
